In [1]:
import theano
import theano.tensor as T
import numpy as np

## 对序列中的每个元素都执行fn函数

In [2]:
def fn(x):
    return x + 1

In [3]:
a = T.matrix()
results, updates = theano.scan(fn, sequences=a)
f = theano.function([a], results, updates=updates)

In [4]:
matrix = np.ones((2,3))
matrix

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
f(matrix.astype(theano.config.floatX))

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [6]:
a = T.vector()
results, updates = theano.scan(fn, sequences=a)
f = theano.function([a], results, updates=updates)

In [7]:
vector = np.array([1,2,3])

In [8]:
f(vector.astype(theano.config.floatX))

array([ 2.,  3.,  4.])